--- 
- name: copy files 
  hosts: all 
  become: true 
  tasks: 
  - name: copy index.html file 
    copy: 
      src: /opt/ansible/index.html 
      des: /home/ansadmin 
      mode: 755
      mode: user 







#   sudo vi copyfile.yml
#   ansible-playbook copyfiles.yml