--- 
- name: craete a file 
  hosts: all 
  become: true 
  - name: create a file 
    file: 
      path: /home/ansadmin/file1 
      state: touch 
    





#   sudo vi createfile.yml
#   ansible-playbook craete file.yml




# create directory.yml 
---
- name: craete directory playbook 
  hosts: all 
  become: true 
  tasks:
  - name: create a directory 
    file: 
     path: /home/ansadmin/directory 
     state: dir 




#   sudo vi directory.yml 
#   ansible-playbook directory.yml 